name: Actions Workflow

on: 
  #push:
  pull_request:
    types: [assigned, closed, opened, reopened]
  repository_dispatch:
    types: [build]   # w/o build it would run on any type
  schedule:
    - cron: "0 12 * FEB 2"
    - cron: "0 12 * JAN 2"

jobs:
  run-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: list-envs
        run: declare -p

      - name: list-files-BEFORE-checkout
        run: |
          pwd
          ls -altr
          git status 2>/dev/null || echo "Not a git repo!"

      - name: checkout
        uses: actions/checkout@v1   # checkouts the code from the commit that triggered this action

      - name: list-files-AFTER-checkout
        run: |
          pwd
          ls -altr
          git status

      - name: hello-from-js
        id: greet
        uses: actions/hello-world-javascript-action@v1.1  # this is puslished action on GitHub, can use master (branch name) or SHA of the specific commit, SHA is safest way!
        with:
          who-to-greet: Jo2o
      
      - name: log-greeting-time
        run: echo "${{ steps.greet.outputs.time }}"

      - name: log-request-payload
        run: echo "Env from request's body: ${{ github.event.client_payload.env }}"
