name: Shell Commands

on: [push]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: RunEcho
        run: echo "Running echo..."

      - name: CheckVersions
        run: |
          node -v
          npm -v

      - name: SomePython
        shell: python
        run: |
          import platform
          print('Platform processor is: ' + platform.processor())

  run-windows:
    runs-on: windows-latest
    steps:
      - name: Win-Powershell
        run: Get-Location

      - name: Win-Bash
        run: pwd
        shell: bash
        
