name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: RunEcho
        run: echo "Running echo..."
      - name: CheckVersions
        run: |
          node -v
          npm -v